import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';

import 'package:loading_animation_widget/loading_animation_widget.dart';

class Autogenerated {
  int? id;
  String? name;
  String? username;
  String? email;
  Address? address;
  String? phone;
  String? website;
  Company? company;

  Autogenerated(
      {this.id,
      this.name,
      this.username,
      this.email,
      this.address,
      this.phone,
      this.website,
      this.company});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    username = json['username'];
    email = json['email'];
    address =
        json['address'] != null ? new Address.fromJson(json['address']) : null;
    phone = json['phone'];
    website = json['website'];
    company =
        json['company'] != null ? new Company.fromJson(json['company']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['username'] = this.username;
    data['email'] = this.email;
    if (this.address != null) {
      data['address'] = this.address!.toJson();
    }
    data['phone'] = this.phone;
    data['website'] = this.website;
    if (this.company != null) {
      data['company'] = this.company!.toJson();
    }
    return data;
  }
}

class Address {
  String? street;
  String? suite;
  String? city;
  String? zipcode;
  Geo? geo;

  Address({this.street, this.suite, this.city, this.zipcode, this.geo});

  Address.fromJson(Map<String, dynamic> json) {
    street = json['street'];
    suite = json['suite'];
    city = json['city'];
    zipcode = json['zipcode'];
    geo = json['geo'] != null ? new Geo.fromJson(json['geo']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['street'] = this.street;
    data['suite'] = this.suite;
    data['city'] = this.city;
    data['zipcode'] = this.zipcode;
    if (this.geo != null) {
      data['geo'] = this.geo!.toJson();
    }
    return data;
  }
}

class Geo {
  String? lat;
  String? lng;

  Geo({this.lat, this.lng});

  Geo.fromJson(Map<String, dynamic> json) {
    lat = json['lat'];
    lng = json['lng'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['lat'] = this.lat;
    data['lng'] = this.lng;
    return data;
  }
}

class Company {
  String? name;
  String? catchPhrase;
  String? bs;

  Company({this.name, this.catchPhrase, this.bs});

  Company.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    catchPhrase = json['catchPhrase'];
    bs = json['bs'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['catchPhrase'] = this.catchPhrase;
    data['bs'] = this.bs;
    return data;
  }
}

class CustomeUserApi extends StatefulWidget {
  const CustomeUserApi({super.key});

  @override
  State<CustomeUserApi> createState() => _CustomeUserApiState();
}

class _CustomeUserApiState extends State<CustomeUserApi> {
  List<Autogenerated> listOfUser = []; // Here is an empty list

  Future<List<Autogenerated>> getUserApis() async {
    var responseOfUserApis = await http.get(
      Uri.parse('https://jsonplaceholder.typicode.com/users'),
    );
    var decodedData = jsonDecode(responseOfUserApis.body);
    if (responseOfUserApis.statusCode == 200) {
      for (Map<String, dynamic> i in decodedData) {
        var userObject = Autogenerated.fromJson(i);
        listOfUser.add(userObject);
      }
      return listOfUser;
    } else {
      return listOfUser;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        SizedBox(
          height: 8,
        ),
        Expanded(
          child: FutureBuilder(
            future: getUserApis(),
            builder: (context, snapshot) {
              if (!snapshot.hasData) {
                return Center(
                  child: LoadingAnimationWidget.flickr(
                      leftDotColor: Colors.orange,
                      rightDotColor: Colors.green,
                      size: 50),
                );
              } else {
                return ListView.builder(
                  itemCount: listOfUser.length,
                  itemBuilder: (context, index) {
                    return Padding(
                      padding: const EdgeInsets.all(18.0),
                      child: Container(
                        // margin: EdgeInsets.all(10), it applies outside the container.
                        padding: EdgeInsets.all(10), // Inside the container
                        width: double.infinity,
                        height: 270,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(20),
                          boxShadow: [
                            BoxShadow(
                              blurRadius: 4.5,
                              blurStyle: BlurStyle.outer,
                            ),
                          ],
                          color: Colors.white,
                        ),
                        child: Column(
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          spacing: 5,
                          children: [
                            Text(
                              'Name: ${listOfUser[index].name}',
                            ),
                            Text(
                              'Username: ${listOfUser[index].username}',
                            ),
                            Text(
                              'Email: ${listOfUser[index].email}',
                            ),
                            Text(
                              'Id: ${listOfUser[index].id.toString()}',
                            ),
                            Text(
                              'Company name: ${listOfUser[index].company?.name}',
                            ),
                            Text(
                              'Address: ${listOfUser[index].address?.city}',
                            ),
                            Text(
                              'Street: ${listOfUser[index].address?.street}',
                            ),
                            Text(
                              'Geo: ${listOfUser[index].address?.geo?.lng}',
                            ),
                            Text(
                              'Phone: ${listOfUser[index].phone}',
                            ),
                            Text(
                              'Websites: ${listOfUser[index].website}',
                            ),
                          ],
                        ),
                      ),
                    );
                  },
                );
              }
            },
          ),
        ),
      ],
    );
  }
}
